---
name: Sudo
author: WinterBuild7074
version: 1.0.0
api: [3.0.0-ALPHA7]
main: WinterBuild7074\Sudo\Main
commands:
  as:
    description: "Sudo a player"
    permission: "sudo"
  run-as:
    description: "Sudo a player"
    permission: "sudo"
  sudo:
    description: "Sudo a player"
    permission: "sudo"

permissions:
  sudo:
    description: "Allow players to sudo another player"
...
